export const accountTypeList = [
  {
    id: 3007,
    parentId: 306,
    name: "Bank Of Kathmandu Ltd. -  - Current",
    lf: "A.1.2.2.09",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 4471,
    parentId: 307,
    name: "Citizens Bank International Ltd. - 1480100000011301 - Call",
    lf: "A.1.2.3.8",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3005,
    parentId: 307,
    name: "Citizens Bank International Ltd. - 1480100000192201 - Current",
    lf: "A.1.2.3.3",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3063,
    parentId: 309,
    name: "First Microfinance Development Bank Ltd. -  - Current",
    lf: "A.1.2.5.1",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3008,
    parentId: 306,
    name: "Himalayan Bank Ltd. -  - Current",
    lf: "A.1.2.2.10",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3335,
    parentId: 306,
    name: "Nepal Bangladesh Bank",
    lf: "A.1.2.2.15",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3340,
    parentId: 306,
    name: "Nepal Bank Ltd. -  - Current",
    lf: "A.1.2.2.17",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3334,
    parentId: 306,
    name: "NIC ASIA Bank",
    lf: "A.1.2.2.14",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3009,
    parentId: 306,
    name: "Nmb Bank Ltd. -  - Current",
    lf: "A.1.2.2.11",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3167,
    parentId: 306,
    name: "Prime Bank - 14700003CA - Current",
    lf: "A.1.2.2.13",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3336,
    parentId: 306,
    name: "Prime Commerial Bank",
    lf: "A.1.2.2.16",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3339,
    parentId: 308,
    name: "Rastriya Sahakari Bank -  - Current",
    lf: "A.1.2.4.2",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3338,
    parentId: 308,
    name: "Rastriya Sahakari Bank - - Current ",
    lf: "A.1.2.4.1",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
  {
    id: 3549,
    parentId: 308,
    name: "Rmdc Laghubitta Bittiya Sansthak Ltd - Current  -  - Current",
    lf: "A.1.2.4.5",
    groupId: 4,
    type: "B",
    accountId: 0,
  },
];
